### PR TITLE
Dan table wrapper

### PR DESCRIPTION
**Pull request by chillenberger**
- add wrapper to doc tables to allow overflow scroll. 

https://github.com/postgresml/postgresml/assets/39170265/c2b0efa6-f09b-4b95-9510-ae87eb7a62c7

### CODE REVIEW

**Comment by levkk** [comment]
Seems simple enough but why not modify our Markdown parser to add a `div` wrapper with the right classes to the tables?

**Comment by chillenberger** [comment]
> Seems simple enough but why not modify our Markdown parser to add a `div` wrapper with the right classes to the tables?

Are you talking about https://github.com/postgresml/postgresml/blob/7e4b51fe5eed52776b7966c71ec64f8b6f424060/pgml-dashboard/src/utils/markdown.rs#L757?

**Comment by levkk** [comment]
> > Seems simple enough but why not modify our Markdown parser to add a `div` wrapper with the right classes to the tables?
> 
> Are you talking about
> 
> https://github.com/postgresml/postgresml/blob/7e4b51fe5eed52776b7966c71ec64f8b6f424060/pgml-dashboard/src/utils/markdown.rs#L757
> ?

Yup

**Comment by chillenberger** [comment]
Looking into how to do this now.

**Review by levkk — APPROVED** [review]
Awesome!

**Pull request merged**
