### PR TITLE
float compare with tolerance for Apple M2

### PR DESCRIPTION
**Pull request by kczimm**
Added floating point comparison using tolerances to failing tests on Apple M2 silicon.

### CODE REVIEW

**Comment by levkk** [comment]
Our CI is broken right now, need to bust the tooling cache: https://github.com/postgresml/postgresml/blob/master/.github/workflows/ci.yml#L36

Just replace `-1-` with `-2-` or something like that, and it should work.

**Comment by levkk** [comment]
Oh yeah I should mention, without the cache the tests take about 45-50 min to run :)

**Comment by levkk** [comment]
Up to you! Could probably do all of them, but if they are not broken, no need to fix it either. Just thinking out loud.

**Comment by kczimm** [comment]
I could be convinced either way. At the moment, I'm leaning towards minimal changes to pass tests.

**Comment by levkk** [comment]
Sounds good to me.

**Pull request merged**
