### PR TITLE
NVIDIA Image support for pgml

### PR DESCRIPTION
**Pull request by jsaied99**
Adding Baseline NVIDIA Image for PostgresML. Solving [issue](https://github.com/postgresml/postgresml/issues/640).

### CODE REVIEW

**Comment by levkk** [comment]
I'm still getting this:

```
pgml_development=# SELECT pgml.embed('intfloat/e5-small', 'hi mom');
pgml_development=# SELECT pgml.embed('intfloat/e5-small', 'hi mom', '{"device": "cuda"}');
ERROR:  called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'RuntimeError'>, value: RuntimeError('Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx'), traceback: Some(<traceback object at 0x7ff503fca800>) }
pgml_development=#
```

```
nvidia-smi
Thu Jun  1 09:46:09 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 Ti      On | 00000000:08:00.0 Off |                  N/A |
|  0%   46C    P5               34W / 290W|   1044MiB /  8192MiB |     23%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by jsaied99** [comment]
Are you passing the `--gpus` flag? Or if you are using compose, you can try this:

`deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
`

**Comment by levkk** [comment]
```
 docker-compose up
Starting postgresml_docs_1       ... done
Recreating postgresml_postgres_1 ... error

ERROR: for postgresml_postgres_1  Cannot start service postgres: could not select device driver "nvidia" with capabilities: [[gpu]]

```

```
version: "3"
services:
  postgres:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 100
    build:
      context: ./pgml-extension/
      dockerfile: Dockerfile.local
    ports:
      - "5433:5432"
    command:
      - sleep
      - infinity
  dashboard:
    depends_on:
       postgres:
         condition: service_healthy
    build:
      context: ./pgml-dashboard/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pgml_development
    command: bash -c "sqlx migrate run && cargo run"
  docs:
    build:
      context: ./pgml-docs/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command:
      - mkdocs
      - serve
      - -a 0.0.0.0:8001
```

**Comment by jsaied99** [comment]
Do you have the nvidia container toolkit? [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-docker#ubuntu-16041804-debian-jessiestretchbuster%5B/url%5D)

**Comment by montanalow** [comment]
Closing in favor of #681. Thanks @jsaied99!

**Pull request closed without merging**
