### PR TITLE
Repeatable model training

### PR DESCRIPTION
**Pull request by samdobson**
Goal of this PR is to be able to fit a classifier twice, to the same training data, and get the same result.

This code currently does not work, and it's not immediately clear why.
_Edit: now fixed (see below)_

### CODE REVIEW

**Comment by montanalow** [comment]
[random ordering is here](https://github.com/postgresml/postgresml/blob/master/pgml-extension/pgml_extension/model.py#L228)

**Comment by samdobson** [comment]
Thanks both. By not passing the relation second time around, this is now working as expected and model training is now reproducible by default.

**Comment by levkk** [comment]
Ah so `random_state` is not an argument accepted by all algorithms it seems.

**Comment by samdobson** [comment]
My bad, will fix...

**Comment by montanalow** [comment]
I found the issue while I was fixing test_sampling so included the additional fix in #104.

**Comment by samdobson** [comment]
Apologies and thanks. Note to self: run tests first!

**Pull request merged**
